const app = Vue.createApp({

  data: () => ({
    ze: 'ぜ。',
    jya: 'じゃ。',
    ru:'る。',
    ya: 'や。',
    yat: 'や、',
    yas:'や',
    yade: 'やで。',
    ta: 'た。',
    nande: 'なんで',
    shinaika: 'しないか。',
    month: '8',
    day: '16',
    dow: '水',
    hour: '07',
    minute: '14',
    second: '22',
    yMonth: '8',
    yDay: '15',
    yesterday: '昨日',
    asu: '明日',
    yasumi: '休み',
    age: '歳',
    furousha: '浮浪者',
    ossan: 'おっさん',
    ossanAge: '60',
    ossan3: '165*75*60',
    send: 'メール',
    like: '汚れ',
    dokata: '土方',
    nichan: '兄ちゃん',
    niichan: 'にいちゃん',
    niichanAge:'45',
    me: 'わし',
    meAge: '53',
    author: '変態糞土方',
    washi3: '163*90*53',
    oyaji: '親父',
    okayama: '岡山の県北',
    kenboku: '県北',
    underLiver: '川の土手の下',
    konbini: 'コンビニ',
    hito: '人',
    sake: '酒',
    nonde: '飲んで',
    tsumami: 'つまみ',
    dikatabi: '地下足袋',
    ichidiku: 'いちぢく浣腸',
    sanbon:'3本',
    poop: '糞',
    dobaah: 'ドバーっ',
    exit: '出口',
    piss: '小便',
    kanchou: '浣腸',
    shasei: '射精',
    otokojiru: '男汁',
    nikai: '二回',
    mail: 'メール',
    sugata: '土方姿',
    chinpo: 'ちんぽ',
    ketsunoana: 'けつの穴',
    hikuhiku: 'ひくひく',
    nameru: '舐め',
    nameruKana: 'なめ',
    stomach: '腹',
    guruguru: 'ぐるぐる',
    mouth: '口',
    face: '顔',
    hand: '手',
    karada: '体',
    waist: '腰',
  })
});
app.mount('#app');
